"use client";
import { Activity, ArrowLeft, BarChart3, BrainCircuit, Clock3, Download, FlaskConical, LineChart, LogOut, Play, Settings, ShieldCheck, Zap } from "lucide-react";
import Link from "next/link";
import { useMemo,useState } from "react";
import { logout } from "@/app/login/actions";
import type { ReplayResult } from "@/lib/replay/types";

const money=(value:number)=>value.toLocaleString("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:2});
const time=(value:number)=>new Date(value).toLocaleTimeString("en-US",{timeZone:"America/New_York",hour:"numeric",minute:"2-digit"});
const yesterday=()=>{const date=new Date();date.setDate(date.getDate()-1);while([0,6].includes(date.getDay()))date.setDate(date.getDate()-1);return date.toISOString().slice(0,10);};

export function ReplayLabView({userEmail}:{userEmail:string|null}){
  const [underlying,setUnderlying]=useState<"SPY"|"SPX">("SPX"); const [sessionDate,setSessionDate]=useState(yesterday); const [dte,setDte]=useState<0|1|2>(0);
  const [running,setRunning]=useState(false); const [error,setError]=useState<string|null>(null); const [result,setResult]=useState<ReplayResult|null>(null);
  const maxDate=useMemo(yesterday,[]);
  async function run(){setRunning(true);setError(null);try{const response=await fetch("/api/replay",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({underlying,sessionDate,dte})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Replay failed");setResult(payload);}catch(value){setError(value instanceof Error?value.message:"Replay failed");}finally{setRunning(false);}}
  function exportReport(){if(!result)return;const blob=new Blob([JSON.stringify(result,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`${result.underlying}-${result.sessionDate}-${result.dte}dte-replay.json`;anchor.click();URL.revokeObjectURL(url);}
  return <div className="terminal-layout"><aside className="sidebar"><div className="brand-mark"><Zap size={17} fill="currentColor"/> VELOCITY</div><div className="desk-label">OPTIONS DESK</div><nav className="desk-nav"><Link className="nav-item" href="/dashboard"><BarChart3 size={16}/> Command center</Link><span className="nav-item"><Activity size={16}/> Setups <small>Live</small></span><Link className="nav-item active" href="/dashboard/replay"><FlaskConical size={16}/> Replay lab</Link><Link className="nav-item" href="/dashboard/analytics"><LineChart size={16}/> Analytics</Link><Link className="nav-item" href="/dashboard/settings"><Settings size={16}/> Risk settings</Link><span className="nav-item"><BrainCircuit size={16}/> AI review <small>Soon</small></span></nav><div className="sidebar-note"><ShieldCheck size={17}/><div><strong>Research only</strong><span>No orders are submitted</span></div></div></aside>
    <div className="workspace"><header className="topbar"><div><p className="eyebrow">DETERMINISTIC STRATEGY RESEARCH</p><h1>Historical Replay Lab</h1></div><div className="topbar-actions"><Link className="logout-button" href="/dashboard"><ArrowLeft size={14}/> Live desk</Link><form action={logout}><button className="logout-button" title={`Sign out${userEmail?` ${userEmail}`:""}`}><LogOut size={14}/> Sign out</button></form></div></header>
    <main className="dashboard replay-dashboard"><section className="replay-control"><div><label>UNDERLYING</label><div className="symbol-switch">{(["SPX","SPY"] as const).map(symbol=><button key={symbol} className={underlying===symbol?"selected":""} onClick={()=>setUnderlying(symbol)}>{symbol}</button>)}</div></div><div><label>SESSION DATE</label><input type="date" value={sessionDate} max={maxDate} onChange={event=>setSessionDate(event.target.value)}/></div><div><label>EXPIRATION</label><div className="dte-tabs replay-dte">{([0,1,2] as const).map(value=><button key={value} className={dte===value?"selected":""} onClick={()=>setDte(value)}>{value}DTE</button>)}</div></div><button className="run-replay" onClick={()=>void run()} disabled={running||!sessionDate}><Play size={15} fill="currentColor"/>{running?"Reconstructing OPRA quotes…":"Run replay"}</button></section>
    <div className="replay-disclosure"><ShieldCheck size={15}/><span>Replay entries pay the first available ask after a signal; exits receive bids. Missing or non-executable quotes are rejected.</span></div>{error?<div className="system-alert"><span>REPLAY ERROR</span>{error}</div>:null}
    {!result&&!running?<section className="replay-empty"><FlaskConical size={34}/><h2>Test the strategy before trusting it</h2><p>Choose a completed session. The engine will replay one-minute SPY direction, reconstruct nearby SPY or SPX option quotes, enforce the $8 ask and liquidity rules, then calculate realistic bid-side outcomes.</p></section>:null}
    {running?<section className="replay-empty loading-replay"><Activity className="spin" size={34}/><h2>Rebuilding the session</h2><p>Historical chain and OPRA quote retrieval can take up to one minute.</p></section>:null}
    {result?<><section className="replay-summary"><article><span>QUALIFIED SIGNALS</span><strong>{result.summary.signals}</strong></article><article><span>EXECUTABLE TRADES</span><strong>{result.summary.trades}</strong></article><article><span>WIN RATE</span><strong>{result.summary.winRate==null?"—":`${result.summary.winRate.toFixed(1)}%`}</strong></article><article className={result.summary.netPnl>=0?"positive":"negative"}><span>NET P/L · 1 CONTRACT</span><strong>{money(result.summary.netPnl)}</strong></article><article><span>EXPECTANCY</span><strong>{result.summary.expectancy==null?"—":money(result.summary.expectancy)}</strong></article></section>
    <section className="replay-report"><div className="section-heading"><div><span>{result.underlying} · {result.sessionDate} · {result.dte}DTE</span><strong>EVENT REPORT · {result.strategyVersion}</strong></div><button className="export-report" onClick={exportReport}><Download size={14}/> Export JSON</button></div><div className="table-wrap"><table><thead><tr>{["Signal","Decision","Contract","Entry ask","Exit bid","Exit","P/L","Return","MFE","MAE","Volume","Spread"].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{result.trades.length?result.trades.map(trade=><tr key={`${trade.signalTime}-${trade.contractTicker}`}><td>{time(trade.signalTime)}</td><td><span className={`side-pill ${trade.side}`}>{trade.side.toUpperCase()}</span></td><td className="mono contract-ticker">{trade.contractTicker}</td><td>{money(trade.entryAsk)}</td><td>{money(trade.exitBid)}</td><td>{trade.exitReason} · {time(trade.exitTime)}</td><td className={trade.pnlDollars>=0?"profit":"loss"}>{money(trade.pnlDollars)}</td><td>{trade.returnPct.toFixed(1)}%</td><td className="profit">+{trade.mfePct.toFixed(1)}%</td><td className="loss">{trade.maePct.toFixed(1)}%</td><td>{trade.cumulativeVolume.toLocaleString()}</td><td>{trade.spreadPct.toFixed(1)}%</td></tr>):<tr><td colSpan={12} className="empty-dte">No executable trade survived the replay controls.</td></tr>}</tbody></table></div>
    {result.noTradeReasons.length?<div className="replay-notes"><strong>REJECTED / MISSED EVENTS</strong>{result.noTradeReasons.map(reason=><p key={reason}>— {reason}</p>)}</div>:null}<div className="replay-limitations"><strong>READ BEFORE INTERPRETING</strong>{result.limitations.map(item=><p key={item}>{item}</p>)}</div></section></>:null}
    <footer className="risk-footer"><Clock3 size={15}/> One session is evidence, not an edge. Judge the strategy across many sessions and out-of-sample periods.</footer></main></div></div>;
}
