"use client";
import {Activity,BarChart3,BrainCircuit,FlaskConical,Gauge,LineChart,LogOut,Save,Settings,ShieldCheck,Zap} from "lucide-react";
import Link from "next/link";
import {useState} from "react";
import {logout} from "@/app/login/actions";
import type {RiskSettings} from "@/lib/settings/config";

const toTime=(minutes:number)=>`${String(Math.floor(minutes/60)).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`;const fromTime=(value:string)=>{const [hour,minute]=value.split(":").map(Number);return hour*60+minute;};
export function SettingsView({userEmail,initial}:{userEmail:string|null;initial:RiskSettings}){const [value,setValue]=useState(initial);const [baseline,setBaseline]=useState(initial);const [saving,setSaving]=useState(false);const [message,setMessage]=useState<{tone:"success"|"error";text:string}|null>(null);const changed=JSON.stringify(value)!==JSON.stringify(baseline);
  function number<K extends keyof RiskSettings>(key:K,input:string){setValue(current=>({...current,[key]:Number(input)}));}
  function toggleList<K extends "allowedDte"|"allowedUnderlyings">(key:K,item:RiskSettings[K][number]){setValue(current=>{const list=current[key] as Array<typeof item>;return {...current,[key]:list.includes(item)?list.filter(entry=>entry!==item):[...list,item]};});}
  async function save(){setSaving(true);setMessage(null);try{const response=await fetch("/api/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(value)});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Save failed");setValue(payload.settings);setBaseline(payload.settings);setMessage({tone:"success",text:"Risk controls saved. New scans and approvals now use these values."});}catch(error){setMessage({tone:"error",text:error instanceof Error?error.message:"Save failed"});}finally{setSaving(false);}}
  return <div className="terminal-layout"><aside className="sidebar"><div className="brand-mark"><Zap size={17} fill="currentColor"/> VELOCITY</div><div className="desk-label">OPTIONS DESK</div><nav className="desk-nav"><Link className="nav-item" href="/dashboard"><BarChart3 size={16}/> Command center</Link><span className="nav-item"><Activity size={16}/> Setups <small>Live</small></span><Link className="nav-item" href="/dashboard/replay"><FlaskConical size={16}/> Replay lab</Link><Link className="nav-item" href="/dashboard/analytics"><LineChart size={16}/> Analytics</Link><Link className="nav-item active" href="/dashboard/settings"><Settings size={16}/> Risk settings</Link><span className="nav-item"><BrainCircuit size={16}/> AI review <small>Soon</small></span></nav><div className="sidebar-note"><ShieldCheck size={17}/><div><strong>Paper mode only</strong><span>Live execution unavailable</span></div></div></aside><div className="workspace"><header className="topbar"><div><p className="eyebrow">SERVER-ENFORCED CONTROLS</p><h1>Settings & Risk Controls</h1></div><div className="topbar-actions"><form action={logout}><button className="logout-button" title={`Sign out${userEmail?` ${userEmail}`:""}`}><LogOut size={14}/> Sign out</button></form></div></header><main className="dashboard settings-dashboard">
  <section className="settings-warning"><ShieldCheck size={17}/><div><strong>Alpaca paper trading only</strong><span>The application cannot place live orders. Every paper entry still requires explicit approval, and the system retains a hard 1%-of-equity debit ceiling.</span></div></section>{message?<div className={`order-message ${message.tone}`}>{message.text}</div>:null}
  <section className="settings-grid"><SettingsGroup title="CAPITAL AT RISK" icon={<Gauge size={17}/>}><NumberField label="Maximum option ask" prefix="$" value={value.maxOptionAsk} step="0.10" help="Scanner rejects contracts above this ask." onChange={input=>number("maxOptionAsk",input)}/><NumberField label="Maximum debit per trade" prefix="$" value={value.maxTradeDebit} step="10" help="One contract only; the lower of this or 1% of equity applies." onChange={input=>number("maxTradeDebit",input)}/><NumberField label="Daily loss limit" prefix="$" value={value.maxDailyLoss} step="25" help="New entries stop after account equity falls by this amount today." onChange={input=>number("maxDailyLoss",input)}/><NumberField label="Maximum trades per day" value={value.maxTradesPerDay} step="1" help="Counts submitted buy-to-open paper orders." onChange={input=>number("maxTradesPerDay",input)}/><NumberField label="Maximum open positions" value={value.maxOpenPositions} step="1" help="Set to zero to block all new positions." onChange={input=>number("maxOpenPositions",input)}/></SettingsGroup>
  <SettingsGroup title="CONTRACT QUALITY" icon={<Activity size={17}/>}><NumberField label="Minimum contract volume" value={value.minContractVolume} step="50" help="Cumulative session volume required by the scanner." onChange={input=>number("minContractVolume",input)}/><NumberField label="Maximum bid/ask spread" suffix="%" value={value.maxSpreadPct} step="0.5" help="Wider contracts are rejected." onChange={input=>number("maxSpreadPct",input)}/><Choice label="Allowed DTE" options={[0,1,2]} selected={value.allowedDte} format={item=>`${item}DTE`} onToggle={item=>toggleList("allowedDte",item)}/><Choice label="Allowed underlyings" options={["SPY","SPX"] as const} selected={value.allowedUnderlyings} format={item=>item} onToggle={item=>toggleList("allowedUnderlyings",item)}/></SettingsGroup>
  <SettingsGroup title="TRADING WINDOW · ET" icon={<ShieldCheck size={17}/>}><label className="settings-field"><span>Entry start</span><input type="time" min="09:30" max="15:30" value={toTime(value.entryStartMinutes)} onChange={event=>setValue(current=>({...current,entryStartMinutes:fromTime(event.target.value)}))}/><small>Signals before this time cannot be approved.</small></label><label className="settings-field"><span>Entry cutoff</span><input type="time" min="09:45" max="15:45" value={toTime(value.entryEndMinutes)} onChange={event=>setValue(current=>({...current,entryEndMinutes:fromTime(event.target.value)}))}/><small>No new entries after this time.</small></label><Toggle label="Paper entries enabled" detail="Emergency control for new entries. Existing exit management is separate." checked={value.paperTradingEnabled} onChange={checked=>setValue(current=>({...current,paperTradingEnabled:checked}))}/><Toggle label="AI review enabled" detail="Reserved for optional critique. It never overrides deterministic rules." checked={value.aiReviewEnabled} onChange={checked=>setValue(current=>({...current,aiReviewEnabled:checked}))}/></SettingsGroup></section>
  <button className="save-settings" disabled={saving||!changed||!value.allowedDte.length||!value.allowedUnderlyings.length} onClick={()=>void save()}><Save size={15}/>{saving?"Validating…":"Save and enforce settings"}</button><footer className="risk-footer"><ShieldCheck size={15}/> Changes affect future scans and approvals; they do not alter open positions or historical replay results.</footer></main></div></div>;
}
function SettingsGroup({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <article className="settings-card"><div className="settings-card-title">{icon}<strong>{title}</strong></div><div className="settings-fields">{children}</div></article>}
function NumberField({label,value,onChange,help,prefix,suffix,step}:{label:string;value:number;onChange:(value:string)=>void;help:string;prefix?:string;suffix?:string;step:string}){return <label className="settings-field"><span>{label}</span><div className="number-input">{prefix?<i>{prefix}</i>:null}<input type="number" value={value} step={step} onChange={event=>onChange(event.target.value)}/>{suffix?<i>{suffix}</i>:null}</div><small>{help}</small></label>}
function Choice<T extends string|number>({label,options,selected,onToggle,format}:{label:string;options:readonly T[];selected:T[];onToggle:(item:T)=>void;format:(item:T)=>string}){return <div className="settings-field"><span>{label}</span><div className="choice-row">{options.map(item=><button key={item} className={selected.includes(item)?"selected":""} onClick={()=>onToggle(item)}>{format(item)}</button>)}</div></div>}
function Toggle({label,detail,checked,onChange}:{label:string;detail:string;checked:boolean;onChange:(checked:boolean)=>void}){return <label className="toggle-setting"><div><strong>{label}</strong><small>{detail}</small></div><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/><i/></label>}
