"use client";
import {Activity,BarChart3,BrainCircuit,FlaskConical,LineChart,LogOut,ShieldCheck,TrendingDown,TrendingUp,Zap} from "lucide-react";
import Link from "next/link";
import {logout} from "@/app/login/actions";
import type {buildAnalytics,AnalyticsGroup,MetricSet} from "@/lib/analytics/metrics";

type Analytics=ReturnType<typeof buildAnalytics>;
const dollars=(value:number|null)=>value==null?"—":value.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2});
const percent=(value:number|null)=>value==null?"—":`${value.toFixed(1)}%`;
export function AnalyticsView({userEmail,analytics}:{userEmail:string|null;analytics:Analytics}){
  const enough=analytics.overall.trades>=30;
  return <div className="terminal-layout"><aside className="sidebar"><div className="brand-mark"><Zap size={17} fill="currentColor"/> VELOCITY</div><div className="desk-label">OPTIONS DESK</div><nav className="desk-nav"><Link className="nav-item" href="/dashboard"><BarChart3 size={16}/> Command center</Link><span className="nav-item"><Activity size={16}/> Setups <small>Live</small></span><Link className="nav-item" href="/dashboard/replay"><FlaskConical size={16}/> Replay lab</Link><Link className="nav-item active" href="/dashboard/analytics"><LineChart size={16}/> Analytics</Link><span className="nav-item"><BrainCircuit size={16}/> AI review <small>Soon</small></span></nav><div className="sidebar-note"><ShieldCheck size={17}/><div><strong>Replay evidence</strong><span>{analytics.overall.trades} simulated trades</span></div></div></aside>
  <div className="workspace"><header className="topbar"><div><p className="eyebrow">EDGE MEASUREMENT · REPLAY FILLS</p><h1>Strategy Analytics</h1></div><div className="topbar-actions"><form action={logout}><button className="logout-button" title={`Sign out${userEmail?` ${userEmail}`:""}`}><LogOut size={14}/> Sign out</button></form></div></header><main className="dashboard analytics-dashboard">
  <section className={`evidence-banner ${enough?"credible":"early"}`}>{enough?<TrendingUp size={18}/>:<ShieldCheck size={18}/>}<div><strong>{enough?"EARLY SAMPLE AVAILABLE":"INSUFFICIENT SAMPLE"}</strong><span>{enough?"There are enough trades to begin comparing segments, but not to claim a durable edge.":`Collect at least 30 comparable replay trades before interpreting win rate or expectancy. Current sample: ${analytics.overall.trades}.`}</span></div></section>
  <section className="analytics-kpis"><Metric label="TRADES" value={`${analytics.overall.trades}`}/><Metric label="WIN RATE" value={percent(analytics.overall.winRate)}/><Metric label="EXPECTANCY / TRADE" value={dollars(analytics.overall.expectancy)} tone={(analytics.overall.expectancy??0)>=0?"positive":"negative"}/><Metric label="PROFIT FACTOR" value={analytics.overall.profitFactor?.toFixed(2)??"—"}/><Metric label="NET P/L · 1 CONTRACT" value={dollars(analytics.overall.netPnl)} tone={analytics.overall.netPnl>=0?"positive":"negative"}/><Metric label="MAX DRAWDOWN" value={dollars(analytics.overall.maxDrawdown)} tone="negative"/></section>
  {analytics.overall.trades===0?<section className="replay-empty analytics-empty"><LineChart size={36}/><h2>No completed replay trades yet</h2><p>Run historical sessions in the Replay Lab. Executable ask-entry/bid-exit results will appear here automatically.</p><Link className="run-replay" href="/dashboard/replay"><FlaskConical size={14}/> Open replay lab</Link></section>:<>
  <section className="analytics-grid"><Breakdown title="UNDERLYING" rows={analytics.byUnderlying}/><Breakdown title="DAYS TO EXPIRATION" rows={analytics.byDte}/><Breakdown title="DIRECTION" rows={analytics.bySide}/><Breakdown title="TIME OF DAY · ET" rows={analytics.byTime}/><Breakdown title="ENTRY PREMIUM" rows={analytics.byPremium}/><article className="analytics-card diagnostic-card"><div className="section-heading"><div><span>EXECUTION DIAGNOSTICS</span><strong>AVERAGE RESULTS</strong></div></div><div className="diagnostic-list"><MetricLine label="Average winner" value={dollars(analytics.overall.averageWin)} positive/><MetricLine label="Average loser" value={dollars(analytics.overall.averageLoss)}/><MetricLine label="Average entry spread" value={percent(analytics.overall.averageSpread)}/><MetricLine label="Profit factor" value={analytics.overall.profitFactor?.toFixed(2)??"—"}/></div></article></section>
  <section className="sample-card"><div className="section-heading"><div><span>VALIDATION DISCIPLINE</span><strong>CHRONOLOGICAL 70 / 30 SPLIT</strong></div></div>{analytics.sample?<div className="sample-comparison"><Sample label={`IN-SAMPLE · FIRST ${analytics.sample.split}`} metrics={analytics.sample.inSample}/><div className="sample-arrow">→</div><Sample label={`OUT-OF-SAMPLE · LAST ${analytics.overall.trades-analytics.sample.split}`} metrics={analytics.sample.outOfSample}/></div>:<p>At least 10 trades are required before showing an in-sample versus out-of-sample comparison. The split is chronological, never randomized.</p>}</section></>}
  <footer className="risk-footer"><ShieldCheck size={15}/> These are simulated replay results, not live performance. A segment with only a few trades is not evidence of an edge.</footer></main></div></div>;
}
function Metric({label,value,tone=""}:{label:string;value:string;tone?:string}){return <article className={`analytics-kpi ${tone}`}><span>{label}</span><strong>{value}</strong></article>}
function Breakdown({title,rows}:{title:string;rows:AnalyticsGroup[]}){return <article className="analytics-card"><div className="section-heading"><div><span>SEGMENT ANALYSIS</span><strong>{title}</strong></div></div><div className="breakdown-table"><div className="breakdown-head"><span>SEGMENT</span><span>N</span><span>WIN</span><span>EXPECT.</span><span>PF</span><span>NET</span></div>{rows.map(row=><div className="breakdown-row" key={row.key}><strong>{row.label}</strong><span>{row.trades}</span><span>{percent(row.winRate)}</span><span className={(row.expectancy??0)>=0?"profit":"loss"}>{dollars(row.expectancy)}</span><span>{row.profitFactor?.toFixed(2)??"—"}</span><span className={row.netPnl>=0?"profit":"loss"}>{dollars(row.netPnl)}</span></div>)}</div></article>}
function MetricLine({label,value,positive=false}:{label:string;value:string;positive?:boolean}){return <div><span>{label}</span><strong className={positive?"profit":""}>{value}</strong></div>}
function Sample({label,metrics}:{label:string;metrics:MetricSet}){return <div className="sample-side"><strong>{label}</strong><div><span>Trades</span><b>{metrics.trades}</b></div><div><span>Win rate</span><b>{percent(metrics.winRate)}</b></div><div><span>Expectancy</span><b className={(metrics.expectancy??0)>=0?"profit":"loss"}>{dollars(metrics.expectancy)}</b></div><div><span>Profit factor</span><b>{metrics.profitFactor?.toFixed(2)??"—"}</b></div></div>}
