create table public.paper_trade_orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  signal_id text not null references public.option_signals(signal_id) on delete restrict,
  constraint paper_trade_orders_signal_unique unique (signal_id),
  alpaca_order_id text not null unique,
  client_order_id text not null unique,
  action text not null check (action in ('buy_to_open', 'sell_to_close')),
  underlying text not null check (underlying in ('SPY', 'SPX')),
  contract_ticker text not null,
  quantity integer not null check (quantity > 0),
  order_type text not null check (order_type = 'limit'),
  limit_price numeric(12, 4) not null check (limit_price > 0),
  max_debit numeric(12, 2) not null check (max_debit > 0),
  status text not null,
  risk_snapshot jsonb not null,
  broker_response jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index paper_trade_orders_created_at_idx on public.paper_trade_orders (created_at desc);
create index paper_trade_orders_contract_idx on public.paper_trade_orders (contract_ticker, created_at desc);
alter table public.paper_trade_orders enable row level security;
revoke all on public.paper_trade_orders from anon, authenticated;
grant all on public.paper_trade_orders to service_role;
comment on table public.paper_trade_orders is 'Server-only audit journal for explicitly approved Alpaca paper option orders.';
