import {z} from "zod";

export const riskSettingsSchema=z.object({
  maxOptionAsk:z.number().min(.1).max(20),maxTradeDebit:z.number().min(10).max(10000),maxDailyLoss:z.number().min(10).max(25000),
  maxTradesPerDay:z.number().int().min(1).max(20),allowedUnderlyings:z.array(z.enum(["SPY","SPX"])).min(1),allowedDte:z.array(z.union([z.literal(0),z.literal(1),z.literal(2)])).min(1),
  minContractVolume:z.number().int().min(0).max(10_000_000),maxSpreadPct:z.number().min(.1).max(50),maxOpenPositions:z.number().int().min(0).max(5),
  entryStartMinutes:z.number().int().min(570).max(930),entryEndMinutes:z.number().int().min(585).max(945),paperTradingEnabled:z.boolean(),aiReviewEnabled:z.boolean(),
}).refine(value=>value.entryStartMinutes<value.entryEndMinutes,{message:"Entry start must be before entry cutoff",path:["entryEndMinutes"]});
export type RiskSettings=z.infer<typeof riskSettingsSchema>;
export const DEFAULT_RISK_SETTINGS:RiskSettings={maxOptionAsk:8,maxTradeDebit:800,maxDailyLoss:500,maxTradesPerDay:3,allowedUnderlyings:["SPY","SPX"],allowedDte:[0,1,2],minContractVolume:100,maxSpreadPct:10,maxOpenPositions:1,entryStartMinutes:585,entryEndMinutes:885,paperTradingEnabled:true,aiReviewEnabled:false};
type Row=Record<string,unknown>;
export function settingsFromRow(row:Row|null|undefined):RiskSettings{return riskSettingsSchema.parse({maxOptionAsk:Number(row?.max_option_ask??DEFAULT_RISK_SETTINGS.maxOptionAsk),maxTradeDebit:Number(row?.max_trade_debit??DEFAULT_RISK_SETTINGS.maxTradeDebit),maxDailyLoss:Number(row?.max_daily_loss??DEFAULT_RISK_SETTINGS.maxDailyLoss),maxTradesPerDay:Number(row?.max_trades_per_day??DEFAULT_RISK_SETTINGS.maxTradesPerDay),allowedUnderlyings:row?.allowed_underlyings??DEFAULT_RISK_SETTINGS.allowedUnderlyings,allowedDte:row?.allowed_dte??DEFAULT_RISK_SETTINGS.allowedDte,minContractVolume:Number(row?.min_contract_volume??DEFAULT_RISK_SETTINGS.minContractVolume),maxSpreadPct:Number(row?.max_spread_pct??DEFAULT_RISK_SETTINGS.maxSpreadPct),maxOpenPositions:Number(row?.max_open_positions??DEFAULT_RISK_SETTINGS.maxOpenPositions),entryStartMinutes:Number(row?.entry_start_minutes??DEFAULT_RISK_SETTINGS.entryStartMinutes),entryEndMinutes:Number(row?.entry_end_minutes??DEFAULT_RISK_SETTINGS.entryEndMinutes),paperTradingEnabled:row?.paper_trading_enabled??DEFAULT_RISK_SETTINGS.paperTradingEnabled,aiReviewEnabled:row?.ai_review_enabled??DEFAULT_RISK_SETTINGS.aiReviewEnabled});}
export function settingsToRow(value:RiskSettings){return {max_option_ask:value.maxOptionAsk,max_trade_debit:value.maxTradeDebit,max_daily_loss:value.maxDailyLoss,max_trades_per_day:value.maxTradesPerDay,allowed_underlyings:value.allowedUnderlyings,allowed_dte:value.allowedDte,min_contract_volume:value.minContractVolume,max_spread_pct:value.maxSpreadPct,max_open_positions:value.maxOpenPositions,entry_start_minutes:value.entryStartMinutes,entry_end_minutes:value.entryEndMinutes,paper_trading_enabled:value.paperTradingEnabled,ai_review_enabled:value.aiReviewEnabled,updated_at:new Date().toISOString()};}
